In [16]:
import pandas as pd

In [17]:
data = pd.read_csv('../data/TML-Database/2025.csv')

In [18]:
data

,tourney_id,tourney_name,surface,draw_size,tourney_level,indoor,tourney_date,match_num,winner_id,winner_seed,...,w_bpFaced,l_ace,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced
0,2025-9900,United Cup,Hard,18.0,A,O,20241229,1.0,CD85,NaN,...,2.0,3.0,4.0,42.0,24.0,14.0,4.0,7.0,2.0,7.0
1,2025-9900,United Cup,Hard,18.0,A,O,20241229,2.0,Z371,NaN,...,0.0,3.0,2.0,35.0,22.0,13.0,3.0,7.0,1.0,5.0
2,2025-9900,United Cup,Hard,18.0,A,O,20241229,3.0,TE51,NaN,...,3.0,2.0,3.0,92.0,70.0,48.0,9.0,14.0,6.0,9.0
3,2025-9900,United Cup,Hard,18.0,A,O,20241229,4.0,CG80,NaN,...,10.0,13.0,3.0,90.0,67.0,43.0,11.0,13.0,8.0,12.0
4,2025-9900,United Cup,Hard,18.0,A,O,20241229,5.0,HH26,NaN,...,1.0,10.0,1.0,56.0,34.0,27.0,10.0,10.0,1.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2939,2025-7696,Next Gen ATP Finals,Hard,8.0,A,I,20251222,11.0,B0NN,6.0,...,2.0,14.0,6.0,80.0,50.0,38.0,13.0,12.0,3.0,6.0
2940,2025-7696,Next Gen ATP Finals,Hard,8.0,A,I,20251222,12.0,B0U4,5.0,...,4.0,4.0,3.0,78.0,50.0,36.0,10.0,12.0,4.0,9.0
2941,2025-7696,Next Gen ATP Finals,Hard,8.0,A,I,20251222,13.0,T0HA,1.0,...,9.0,6.0,2.0,50.0,33.0,21.0,10.0,9.0,1.0,4.0
2942,2025-7696,Next Gen ATP Finals,Hard,8.0,A,I,20251222,14.0,B0PG,2.0,...,7.0,10.0,0.0,63.0,44.0,34.0,9.0,9.0,4.0,6.0
2943,2025-7696,Next Gen ATP Finals,Hard,8.0,A,I,20251222,15.0,T0HA,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
jannik_sinner = data[(data['winner_name'] == 'Jannik Sinner') | (data['loser_name'] == 'Jannik Sinner')]

In [20]:
jannik_sinner

,tourney_id,tourney_name,surface,draw_size,tourney_level,indoor,tourney_date,match_num,winner_id,winner_seed,...,w_bpFaced,l_ace,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced
163,2025-580,Australian Open,Hard,128.0,G,O,20250113,27.0,S0AG,1.0,...,2.0,13.0,4.0,98.0,71.0,52.0,13.0,15.0,3.0,5.0
201,2025-580,Australian Open,Hard,128.0,G,O,20250113,65.0,S0AG,1.0,...,1.0,13.0,10.0,138.0,83.0,59.0,19.0,18.0,8.0,13.0
233,2025-580,Australian Open,Hard,128.0,G,O,20250113,97.0,S0AG,1.0,...,7.0,2.0,2.0,82.0,48.0,32.0,12.0,13.0,5.0,10.0
249,2025-580,Australian Open,Hard,128.0,G,O,20250113,113.0,S0AG,1.0,...,5.0,5.0,4.0,110.0,68.0,45.0,21.0,17.0,4.0,8.0
257,2025-580,Australian Open,Hard,128.0,G,O,20250113,121.0,S0AG,1.0,...,1.0,2.0,1.0,78.0,40.0,26.0,15.0,12.0,4.0,10.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2903,2025-605,ATP Finals,Hard,8.0,F,I,20251110,4.0,S0AG,2.0,...,0.0,9.0,2.0,71.0,47.0,30.0,9.0,9.0,7.0,10.0
2907,2025-605,ATP Finals,Hard,8.0,F,I,20251110,8.0,S0AG,2.0,...,7.0,7.0,0.0,52.0,43.0,31.0,3.0,9.0,2.0,4.0
2910,2025-605,ATP Finals,Hard,8.0,F,I,20251110,11.0,S0AG,2.0,...,1.0,6.0,2.0,66.0,47.0,36.0,8.0,11.0,2.0,4.0
2912,2025-605,ATP Finals,Hard,8.0,F,I,20251110,14.0,S0AG,2.0,...,4.0,8.0,2.0,88.0,46.0,29.0,19.0,10.0,10.0,13.0
2914,2025-605,ATP Finals,Hard,8.0,F,I,20251110,16.0,S0AG,2.0,...,3.0,5.0,0.0,72.0,49.0,36.0,13.0,12.0,0.0,2.0

In [21]:
#count_aces = 0
#for i in range(len(jannik_sinner)):
#    count_aces += jannik_sinner['w_ace'].iloc[i]
#print(count_aces)

# this is a better and faster way to do it using pandas
#count_aces = jannik_sinner['w_ace'].sum()
#print(count_aces)

# this counts aces from winners, which means that in the matches where jannik wasn't the winner, it counts that as well.

# a better approach:
aces_in_match_won = jannik_sinner.loc[jannik_sinner['winner_name'] == 'Jannik Sinner', 'w_ace'].sum()
aces_in_match_lost = jannik_sinner.loc[jannik_sinner['loser_name'] == 'Jannik Sinner', 'l_ace'].sum()

total_aces = aces_in_match_won + aces_in_match_lost

print(total_aces)

405.0

In [22]:
tourneys = data['surface'].unique()
print(tourneys)

<StringArray>
['Hard', 'Clay', 'Grass']
Length: 3, dtype: str

In [23]:
def get_ace_count(data, player_name):
    aces_in_match_won = data.loc[data['winner_name'] == player_name, 'w_ace'].sum()
    aces_in_match_lost = data.loc[data['loser_name'] == player_name, 'l_ace'].sum()

    total_aces = aces_in_match_won + aces_in_match_lost

    return total_aces


print(get_ace_count(data, 'Carlos Alcaraz'))
print(get_ace_count(data, 'Jannik Sinner'))
print(get_ace_count(data, 'Novak Djokovic'))

463.0
405.0
409.0

In [24]:
def get_first_serve_percentage(data, player_name):
    total_service_points_match_won = data.loc[data['winner_name'] == player_name, 'w_svpt'].sum()
    total_first_serves_in_match_won = data.loc[data['winner_name'] == player_name, 'w_1stIn'].sum()

    total_service_points_match_lost = data.loc[data['loser_name'] == player_name, 'l_svpt'].sum()
    total_first_serves_in_match_lost = data.loc[data['loser_name'] == player_name, 'l_1stIn'].sum()

    first_serve_percentage = ((total_first_serves_in_match_lost + total_first_serves_in_match_won) / (total_service_points_match_won + total_service_points_match_lost)) * 100

    return first_serve_percentage

print(get_first_serve_percentage(data, 'Jannik Sinner'))

62.24714160070361

In [32]:
# potential error: ff data has any matches with NaN in the bp columns (retirements, incomplete stats), .
#                  sum() will silently skip them, but your denominator could still be off if faced is present but saved is 
#                  missing (or vice versa) — worth a dropna or a sanity check before trusting this at scale.
def get_break_points_saved_rate(data, player_name):
    total_break_points_faced_in_matches_won = data.loc[data['winner_name'] == player_name, 'w_bpFaced'].sum()
    total_break_points_saved_in_matches_won = data.loc[data['winner_name'] == player_name, 'w_bpSaved'].sum()

    total_break_points_faced_in_matches_lost = data.loc[data['loser_name'] == player_name, 'l_bpFaced'].sum()
    total_break_points_saved_in_matches_lost = data.loc[data['loser_name'] == player_name, 'l_bpSaved'].sum()

    break_points_saved = ((total_break_points_saved_in_matches_won + total_break_points_saved_in_matches_lost) / (total_break_points_faced_in_matches_won + total_break_points_faced_in_matches_lost)) * 100

    return break_points_saved

print(get_break_points_saved_rate(data, 'Jannik Sinner'))

72.32142857142857

In [26]:
# mistakes: no () around each condition
#           wrote 'hard' instead of 'Hard'. Need to pay more attention to spellings
total_surface_matches_won = data[(data['winner_name'] == 'Jannik Sinner') & (data['surface'] == 'Hard')]
len(total_surface_matches_won)

39

In [27]:
def get_surface_win_rate(data, player_name, surface):
    total_surface_matches_won = len(data[(data['winner_name'] == player_name) & (data['surface'] == surface)])
    total_surface_matches_lost = len(data[(data['loser_name'] == player_name) & (data['surface'] == surface)])

    # TODO: Will need to consider division by zero error here. Will Fix later if need be.
    surface_win_rate = (total_surface_matches_won / (total_surface_matches_won + total_surface_matches_lost)) * 100

    return surface_win_rate

print(get_surface_win_rate(data, 'Jannik Sinner', 'Grass'))

88.88888888888889

In [28]:
def head_to_head_record(data, player_one, player_two):
    no_matches_won_by_player_one = len(data[(data['winner_name'] == player_one) & (data['loser_name'] == player_two)])
    no_matches_won_by_player_two = len(data[(data['winner_name'] == player_two) & (data['loser_name'] == player_one)])

    return no_matches_won_by_player_one, no_matches_won_by_player_two

player_one_wins, player_two_wins = head_to_head_record(data, 'Jannik Sinner', 'Carlos Alcaraz')
print(f'{player_one_wins} - {player_two_wins}')

2 - 4

In [81]:
def get_break_points_conversion_rate(data, player_name):
    # formula for calculating breaking points won :-
    #     if the player won the match: loser_break_points_faced - loser_break_points_saved
    #     if the player lost the match: winner_break_points_faced - winner_break_points_saved
    break_points_faced_by_opponent_when_winning = data.loc[data['winner_name'] == player_name, 'l_bpFaced'].sum()
    break_points_saved_by_opponent_when_winning = data.loc[data['winner_name'] == player_name, 'l_bpSaved'].sum()

    break_points_faced_by_opponent_when_losing = data.loc[data['loser_name'] == player_name, 'w_bpFaced'].sum()
    break_points_saved_by_opponent_when_losing = data.loc[data['loser_name'] == player_name, 'w_bpSaved'].sum()

    bp_won = (break_points_faced_by_opponent_when_losing + break_points_faced_by_opponent_when_winning) - (break_points_saved_by_opponent_when_losing + break_points_saved_by_opponent_when_winning)
    total_bp = break_points_faced_by_opponent_when_losing + break_points_faced_by_opponent_when_winning

    bp_conversion_rate = (bp_won / total_bp) * 100

    return bp_conversion_rate


print(get_break_points_conversion_rate(data, 'Jannik Sinner'))

44.584837545126355

In [82]:
def get_first_serve_win_percentage(data, player_name):
    first_serve_points_match_won = data.loc[data['winner_name'] == player_name, 'w_1stIn'].sum()
    first_serves_won_in_match_won = data.loc[data['winner_name'] == player_name, 'w_1stWon'].sum()

    first_serve_points_match_lost = data.loc[data['loser_name'] == player_name, 'l_1stIn'].sum()
    first_serves_won_in_match_lost = data.loc[data['loser_name'] == player_name, 'l_1stWon'].sum()

    first_serve_win_percentage = ((first_serves_won_in_match_lost + first_serves_won_in_match_won) / (first_serve_points_match_won + first_serve_points_match_lost)) * 100

    return first_serve_win_percentage

print(get_first_serve_win_percentage(data, 'Jannik Sinner'))

79.40657011656658

In [42]:
def get_second_serve_win_percentage(data, player_name):
    first_serve_points_match_won = data.loc[data['winner_name'] == player_name, 'w_1stIn'].sum()
    second_serves_won_in_match_won = data.loc[data['winner_name'] == player_name, 'w_2ndWon'].sum()
    total_service_points_match_won = data.loc[data['winner_name'] == player_name, 'w_svpt'].sum()

    first_serve_points_match_lost = data.loc[data['loser_name'] == player_name, 'l_1stIn'].sum()
    second_serves_won_in_match_lost = data.loc[data['loser_name'] == player_name, 'l_2ndWon'].sum()
    total_service_points_match_lost = data.loc[data['loser_name'] == player_name, 'l_svpt'].sum()

    second_serves_won = second_serves_won_in_match_lost + second_serves_won_in_match_won

    total_second_serves = (total_service_points_match_lost + total_service_points_match_won) - (first_serve_points_match_lost + first_serve_points_match_won)

    second_serves_win_percentage = (second_serves_won / total_second_serves) * 100

    return second_serves_win_percentage

print(get_second_serve_win_percentage(data, 'Jannik Sinner'))

58.82352941176471

In [45]:
# one important note: data.loc[data['winner_name'] == player_name, 'w_1stIn'].sum()
# this line of code is repetitive throughout the code so better to put it in a function 
# and calling the function with the column name you want to access.
# So instead of explicitly writing 'w_1stIn' or 'w_1stWon', we pass this to a function

In [47]:
def get_win_percentage(data, player_name):
    total_matches_won = len(data[(data['winner_name'] == player_name)])
    total_matches_lost = len(data[(data['loser_name'] == player_name)])

    return ((total_matches_won / (total_matches_lost + total_matches_won)) * 100)

print(get_win_percentage(data, 'Jannik Sinner'))

90.625

In [80]:
def get_last_N_win_percentage(data, player_name, N):
    total_matches = data[(data['winner_name'] == player_name) | (data['loser_name'] == player_name)]
    last_N_matches = total_matches[-N:]

    wins_in_last_N_matches = len(last_N_matches[last_N_matches['winner_name'] == player_name])

    return (wins_in_last_N_matches / len(last_N_matches)) * 100
    

print(get_last_N_win_percentage(data, 'Jannik Sinner', 10))

100.0